### ISSUE TITLE
Error running sh installer on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ivosetyadi** [ajobondon/kirana#1]
Error running sh installer on Ubuntu 14.04 LTS 
on line 44
![kirana-ubuntu](https://cloud.githubusercontent.com/assets/8873291/11087685/fe671126-888e-11e5-9843-a099c6e5dbf5.png)

**Comment by ajobondon** [comment]
halo pak. 

terima kasih atas laporannya. Coba di download ulang file installernya trus diinstall kembali. Kalo si Kirana masih bandel, nanti biar dijewer lagi sama bapaknya ya.

**Comment by ivosetyadi** [comment]
:+1:
